## CS231n Numpy Tutorial

In [2]:
import numpy as np

In [3]:
# numpy array's shape is of great concern
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)  

(2, 3)


In [4]:
print(b[0, 0], b[0, 1], b[1, 0]) 

1 2 4


Arrary Creation

In [5]:
# numpy arrary creation
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [6]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


In [7]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [9]:
np.random.random((2,2))

array([[ 0.71483308,  0.88849602],
       [ 0.62161546,  0.87640502]])

## Array Indexing

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# shape is (3, 4)

In [12]:
b = a[:2, 1:3]

In [13]:
print(b)

[[2 3]
 [6 7]]


### Warinig:
A slice of an array is a view into the same data, so modifying it will modify the original array.

In [14]:
print(a[0,1])

2


In [16]:
b[0,0] = 77

In [17]:
print(a[0,1])

77


We can also mix interger indexing with **slice indexing**. However, doing so will yield an array of **lower rank** than the original array. Note that this is quite different from the way that MATLAB handles array slicing.

In [19]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

Two ways of accessing the data in the middle row of the array.

**Mixing integer indexing with slices** yields an array of lower rank,

while **using only slices** yields an array of the same rank as the original array:

In [29]:
row2_rank1 = a[1, :]  # mixing integer indexing with slices

In [30]:
row2_rank2 = a[1:2, :]  # using only slices for indexing

In [23]:
print(row2_rank1, row2_rank1.shape)

[5 6 7 8] (4,)


In [24]:
print(row2_rank2, row2_rank2.shape)

[[5 6 7 8]] (1, 4)


In [25]:
# Another example:
col2_rank1 = a[:, 1]
col2_rank2 = a[:, 1:2]

In [26]:
print(col2_rank1, col2_rank1.shape)

[ 2  6 10] (3,)


In [31]:
print(col2_rank2, col2_rank2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


* When you index into numpy arrays using **slicing**, the resulting array view will always be a **subarray** of the original array. 
* In contrast, integer array indexing allows you to construct **arbitrary arrays** using the data from another array. Here is an example:

In [4]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [6]:
# An equivalent way
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


When using integer array indexing, we can **reuse** the the same element from the source array:

In [7]:
print(a[[0,0],[1,1]])

[2 2]


In [9]:
# Equivalent:
print(np.array([a[0, 1], a[0,1]]))

[2 2]


One useful trick: WE can **select or mutate one element from each row of a matrix** using integer array indexing!

In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [11]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
b = np.array([0, 2, 0, 1])

In [19]:
#  Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[11 16 17 21]


In [21]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

In [22]:
print(a)

[[31  2  3]
 [ 4  5 36]
 [37  8  9]
 [10 41 12]]


* Slicing index : with ":",
* integer index : only one integer

### Boolean arrary indexing

In [24]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [29]:
# Use boolean array indexing to construct a rank 1 array
bool_idx = (a > 2)

In [26]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [27]:
print(a[bool_idx])

[3 4 5 6]


In [28]:
print(a[a>2])

[3 4 5 6]


## Datatypes

Every numpy array is a grid of elements of **the same type**. 

In [30]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int32


In [31]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)

float64


In [32]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype) 

int64


## Array Math

Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

In [33]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [34]:
print(x+y)

[[  6.   8.]
 [ 10.  12.]]


In [36]:
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]


In [37]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [38]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [39]:
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that unlike MATLAB, ** * ** is **elementwise multiplication**, not matrix multiplication. We instead use the **dot function** to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. **dot** is available both as a function in the numpy module and as an instance method of array objects:

In [40]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [47]:
print(x)
print(v)

[[1 2]
 [3 4]]
[ 9 10]


In [43]:
# Inner product of vectors;
print(v.dot(w))
print(np.dot(v, w))

219
219


In [44]:
# Matrix vector prodcut; produce rank 1 array
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [45]:
print(np.dot(v, x))

[39 58]


### It seems that numpy will adjust a rank1 array automatically for matrix / vector product??

In [48]:
# Matrix / Matrix product
print(x.dot(y))
print(np.dot(x, y))
print(np.dot(y, x)) # Order matters

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


#### sum operation

In [49]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. 

The simplest example of this type of operation is transposing a matrix; to **transpose** a matrix, simply use the **T** attribute of an array object:

In [50]:
print(x)

[[1 2]
 [3 4]]


In [51]:
print(x.T)

[[1 3]
 [2 4]]


Note that taking the transpose of a rank 1 array does nothing: