## CS231n Numpy Tutorial

In [1]:
import numpy as np

In [2]:
# numpy array's shape is of great concern
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)  

(2, 3)


In [3]:
print(b[0, 0], b[0, 1], b[1, 0]) 

1 2 4


Arrary Creation

In [4]:
# numpy arrary creation
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [5]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


In [6]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [7]:
d = np.eye(2)
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [8]:
np.random.random((2,2))

array([[ 0.76045436,  0.69089365],
       [ 0.70580533,  0.43529416]])

## Array Indexing

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# shape is (3, 4)

In [10]:
b = a[:2, 1:3]

In [11]:
print(b)

[[2 3]
 [6 7]]


### Warinig:
A slice of an array is a view into the same data, so modifying it will modify the original array.

In [12]:
print(a[0,1])

2


In [13]:
b[0,0] = 77

In [14]:
print(a[0,1])

77


We can also mix interger indexing with **slice indexing**. However, doing so will yield an array of **lower rank** than the original array. Note that this is quite different from the way that MATLAB handles array slicing.

In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

Two ways of accessing the data in the middle row of the array.

**Mixing integer indexing with slices** yields an array of lower rank,

while **using only slices** yields an array of the same rank as the original array:

In [16]:
row2_rank1 = a[1, :]  # mixing integer indexing with slices

In [17]:
row2_rank2 = a[1:2, :]  # using only slices for indexing

In [18]:
print(row2_rank1, row2_rank1.shape)

[5 6 7 8] (4,)


In [19]:
print(row2_rank2, row2_rank2.shape)

[[5 6 7 8]] (1, 4)


In [20]:
# Another example:
col2_rank1 = a[:, 1]
col2_rank2 = a[:, 1:2]

In [21]:
print(col2_rank1, col2_rank1.shape)

[ 2  6 10] (3,)


In [22]:
print(col2_rank2, col2_rank2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


* When you index into numpy arrays using **slicing**, the resulting array view will always be a **subarray** of the original array. 
* In contrast, integer array indexing allows you to construct **arbitrary arrays** using the data from another array. Here is an example:

In [23]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [24]:
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [25]:
# An equivalent way
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


When using integer array indexing, we can **reuse** the the same element from the source array:

In [26]:
print(a[[0,0],[1,1]])

[2 2]


In [27]:
# Equivalent:
print(np.array([a[0, 1], a[0,1]]))

[2 2]


One useful trick: WE can **select or mutate one element from each row of a matrix** using integer array indexing!

In [28]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [29]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
b = np.array([0, 2, 0, 1])

In [31]:
#  Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [32]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

In [33]:
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


* Slicing index : with ":",
* integer index : only one integer

### Boolean arrary indexing

In [34]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [35]:
# Use boolean array indexing to construct a rank 1 array
bool_idx = (a > 2)

In [36]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [37]:
print(a[bool_idx])

[3 4 5 6]


In [38]:
print(a[a>2])

[3 4 5 6]


## Datatypes

Every numpy array is a grid of elements of **the same type**. 

In [39]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int32


In [40]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)

float64


In [41]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype) 

int64


## Array Math

Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

In [42]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [43]:
print(x+y)

[[  6.   8.]
 [ 10.  12.]]


In [44]:
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]


In [45]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [46]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [47]:
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that unlike MATLAB, ** * ** is **elementwise multiplication**, not matrix multiplication. We instead use the **dot function** to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. **dot** is available both as a function in the numpy module and as an instance method of array objects:

In [48]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [49]:
print(x)
print(v)

[[1 2]
 [3 4]]
[ 9 10]


In [50]:
# Inner product of vectors;
print(v.dot(w))
print(np.dot(v, w))

219
219


In [51]:
# Matrix vector prodcut; produce rank 1 array
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [52]:
print(np.dot(v, x))

[39 58]


### It seems that numpy will adjust a rank1 array automatically for matrix / vector product??

In [53]:
# Matrix / Matrix product
print(x.dot(y))
print(np.dot(x, y))
print(np.dot(y, x)) # Order matters

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


#### sum operation

In [54]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. 

The simplest example of this type of operation is transposing a matrix; to **transpose** a matrix, simply use the **T** attribute of an array object:

In [55]:
print(x)

[[1 2]
 [3 4]]


In [56]:
print(x.T)

[[1 3]
 [2 4]]


Note that taking the transpose of a rank 1 array does nothing:

In [57]:
v = np.array([1, 2, 3])

In [58]:
print(v)
print(v.T)

[1 2 3]
[1 2 3]


#### reshape is also an important array manipulation function

Gives a new shape to an array without changing its data.
```python
numpy.reshape(array, newshape, order='C')
```

**order***: {'C','F','A'}, optional* <br>
Read the elements of *array* using this index order, and place the elements into the reshaped array using this index order. 
-  ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. 
-  ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. 
-  Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. 
-  ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

**newshape***:int or tuple of ints*<br>
- The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that **length**. 
- One shape dimension can be **-1**. In this case, the value is inferred from **the length of the array and remaining dimensions**.

### Question here: "and remaining dimensions???

In [59]:
# Let's look at an example of C-like order
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
# Another example:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [62]:
np.reshape(a, (3, -1))  # the unspecified value is inferred to the 2

array([[1, 2],
       [3, 4],
       [5, 6]])

#### tile

Construct an arrary by repeating *A* the number of times given by *reps*.

```python
numpy.tile(A, reps)
```

If reps has length <font color=red>d</font>, the result will have dimension of <font color=red>max(d, A.ndim)<\font>.

If <font color=red>A.ndim < d </font>, *A* is promoted to be d-dimensional by **prepending** new axes.

If <font color=red>A.ndim > d </font>, *reps* is promoted to be *A.ndim* by **prepending** 1's to it. Thus for an *A* of shape (2, 3, 4, 5), a *reps* of (2,2) is treated as (1, 1, 2, 2).

<div class="alert alert-block alert-warning">Note: Although **tile** may be used for broadcasting, it is strongly recommended to use numpy’s **broadcasting** operations and functions.</div>

#### Broadcasting

Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [63]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [64]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [65]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [66]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, **prepend** the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be ***compatible*** in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves **as if it had shape equal to the elementwise maximum of shapes of the two input arrays**.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Some more examples:

In [67]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))
# NOTICE: it doesn't work in this way:
# print(x + w.T)
# because w is rank 1!!


# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


<div class="alert alert-block alert-warning"> We want to use **broadcasting** instead of *np.tile*.</div>

### Explore more
Actually right now we've already known enough about broadcasting to do our research work, but it doesn't hurt to know more about it!<br>
Below is from the [scipy's official document for broadcast](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [68]:
a = np.array([1, 2, 3])
b = 2
a * b

array([2, 4, 6])

We can think of the scalar _b_ being stretched during the arithmetic operation into an array with the same shape as _a_. The new elements in _b_ are simply copies of the original scalar.  

The stretching analogy is only conceptual. NumPy is smart enough to use the original scalar value without actually making copies, so that broadcasting operations are as memory and computationally efficient as possible.

#### General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1

The size of the resulting array is the maximum size along each dimension of the input arrays.

Arrays do not need to have the same number of dimensions. <br>(BUT I personally suggust reshaping them into the same number of dimensions before broadcasting, especially when you are a novice!)

For example, if you have a 256x256x3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:

When either of the dimensions compared is one, the other is used. In other words, ___dimensions with size 1 are stretched or “copied” to match the other.___ <br>
<div class="alert alert-block alert-info"> This is what I think can be used in our rewriting work: to replace np.tile with broadcasting to do the "copying" work.</div>

Some examples:
```python
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

Some examples that shapes do not broadcast:
```python
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

In [69]:
# Some examples in practice
x = np.arange(4)
xx = x.reshape(4, 1)
y = np.ones(5)
z =  np.ones((3, 4))

In [70]:
x.shape

(4,)

In [71]:
y.shape

(5,)

In [72]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [73]:
xx.shape

(4, 1)

In [74]:
y.shape

(5,)

In [75]:
(xx + y).shape

(4, 5)

In [76]:
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [77]:
x.shape

(4,)

In [78]:
z.shape

(3, 4)

In [79]:
(x + z).shape

(3, 4)

In [80]:
x

array([0, 1, 2, 3])

In [81]:
x + z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

Broadcasting provides a convenient way of taking __the outer product__ (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

In [82]:
a = np.array([0, 10, 20, 30])
b = np.array([1, 2, 3])
a[:, np.newaxis] + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Here the <font color=red>*newaxis*</font> index operator inserts a new axis into __a__, making it a two-dimensional 4x1 array. Combining the __4x1__ array with __b__, which has shape __(3,)__, yields a __4x3__ array.

<div class="alert alert-block alert-info"> Here is another [blog article](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) that talks in detail about broadcasting.</div>